spring.application.name=TraineeshipApp
spring.datasource.url=jdbc:mysql://localhost:3306/TraineeshipDB
spring.datasource.username=mysql
spring.datasource.password=mysql
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto =create