spring.application.name=TraineeshipApp
spring.datasource.url=jdbc:mysql://localhost:3306/TraineeshipDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update

